version:     "0008c--14-Feb-2022"
copyright:   "2022"
author:      "C. BinKadal"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/cbkadal/os221/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
